# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'
 
use_frameworks!
 
workspace 'Modularization'
 
target 'App' do
# Pods for App
 
end
 
target 'Common' do
project '../Common/Common'
 
end